import Head from 'next/head'
import Image from 'next/image'
import Nav from 'react-bootstrap/Nav';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>I am.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center mt-4 mb-4">
          <Link href='/'>I am .</Link>
        </h1>
        <Nav className="justify-content-end">
          <Nav.Item>
            <Nav.Link href='/about'>
              about
            </Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link href='/work'>
              <a>work</a>
            </Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link href='/contact'>
              <a>contact</a>
            </Nav.Link>
          </Nav.Item>
        </Nav>
      </main>
    </div>
  )
}

