import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>I am.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-[150px] text-[#535353] w-full h-[50%] ">
          <Link href='/'>I am .</Link>
        </h1>
        <div>
          <li>
            <Link href='/about'>
              <a>about</a>
            </Link>
          </li>
          <li>
            <Link href='/work'>
              <a>work</a>
            </Link>
          </li>
          <li>
            <Link href='/contact'>
              <a>contact</a>
            </Link>
          </li>
        </div>
      </main>
    </div>
  )
}